# Generated by Django 4.2 on 2025-06-13 12:00

from django.db import migrations, models
import uuid


def generate_team_codes(apps, schema_editor):
    Team = apps.get_model('events', 'Team')
    for team in Team.objects.all():
        team.team_code = uuid.uuid4().hex[:8]
        # Ensure uniqueness
        while Team.objects.filter(team_code=team.team_code).exists():
            team.team_code = uuid.uuid4().hex[:8]
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_domain_event_max_team_size_event_min_team_size_and_more'),
    ]

    operations = [        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.RunPython(generate_team_codes),
    ]
