# Generated by Django 5.2.3 on 2025-06-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='27f0841e', editable=False, max_length=8, unique=True),
        ),
    ]
