# Generated by Django 4.2 on 2025-06-13 12:30

from django.db import migrations, models
import uuid


def generate_unique_team_codes(apps, schema_editor):
    Team = apps.get_model('events', 'Team')
    for team in Team.objects.all():
        team.team_code = uuid.uuid4().hex[:8]
        while Team.objects.filter(team_code=team.team_code).exists():
            team.team_code = uuid.uuid4().hex[:8]
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_team_team_code'),
    ]

    operations = [
        migrations.RunPython(generate_unique_team_codes),
    ]
