# Generated by Django 5.0 on 2025-06-13 12:45

from django.db import migrations, models
import uuid


def generate_unique_team_code(apps, schema_editor):
    """Generate unique team codes for existing teams"""
    Team = apps.get_model('events', 'Team')
    for team in Team.objects.all():
        team.team_code = uuid.uuid4().hex[:8]
        # Ensure uniqueness
        while Team.objects.filter(team_code=team.team_code).exists():
            team.team_code = uuid.uuid4().hex[:8]
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.RunPython(generate_unique_team_code),
    ]
