# Generated by Django 5.0 on 2025-06-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_fix_team_code'),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM events_team WHERE team_code IS NULL OR team_code = '';",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
