# Generated by Django 5.2.3 on 2025-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_team_team_code'),
        ('events', '0007_cleanup_teams'),
    ]

    operations = [
    ]
